name: 'Compile LaTeX'
description: 'Compiles LaTeX document to PDF'
inputs:
  root_file:
    description: 'Root LaTeX file to compile'
    required: true
    default: 'main.tex'
outputs:
  pdf_path:
    description: 'Path to the compiled PDF'
    value: 'main.pdf'
runs:
  using: 'composite'
  steps:
    - name: Setup LaTeX with full TeXLive
      shell: bash
      run: |
        echo "Installing TeXLive and required packages..."
        sudo apt-get update -qq
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended
    
    - name: Compile LaTeX document
      shell: bash
      run: |
        echo "Compiling LaTeX document: ${{ inputs.root_file }}"
        
        # Run pdflatex twice to ensure proper cross-references
        pdflatex -interaction=nonstopmode -file-line-error ${{ inputs.root_file }}
        pdflatex -interaction=nonstopmode -file-line-error ${{ inputs.root_file }}
        
        # Check if PDF was generated successfully
        if [ -f "main.pdf" ]; then
          echo "✅ LaTeX compilation successful"
        else
          echo "❌ LaTeX compilation failed"
          if [ -f "main.log" ]; then
            echo "LaTeX error log (last 30 lines):"
            tail -30 main.log
          fi
          exit 1
        fi