name: Build and Test LaTeX PDF Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Add explicit permissions for testing release and pages functionality
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile LaTeX
      uses: ./.github/actions/compile-latex
      with:
        root_file: main.tex
        
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf-pr-${{ github.event.number }}
        path: main.pdf
        retention-days: 30

    # TEST: Try release creation in PR (will be draft)
    - name: Test Release Creation
      uses: softprops/action-gh-release@v1
      with:
        tag_name: test-pr-${{ github.event.number }}
        name: Test Release PR-${{ github.event.number }}
        files: main.pdf
        draft: true
        prerelease: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # TEST: Try GitHub Pages deployment
    - name: Test GitHub Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        destination_dir: test-pr-${{ github.event.number }}
        keep_files: true
        publish_branch: gh-pages
        force_orphan: false
        enable_jekyll: false
        exclude_assets: '.github,sections,*.tex,*.log,*.aux,*.fls,*.fdb_latexmk'